const BUSINESS_KNOWLEDGE_BASE = (() => {
  const categories = [
    {
      id: "lead",
      tag: "Lead qualification",
      role: "Customer",
      themes: ["TikTok comment", "WhatsApp reply", "old lead", "new enquiry", "Instagram DM"],
      needs: ["studio", "1-bedroom", "2-bedroom", "townhouse", "villa"],
      intents: ["buy", "rent", "invest", "move in", "compare options"],
      areas: ["JVC", "Dubai Marina", "Business Bay", "Downtown Dubai", "Dubai Hills", "Arjan", "JLT", "Palm Jumeirah", "Damac Hills", "Meydan"],
      questions: [
        "Interested. Please send details.",
        "How much is it?",
        "Is it still available?",
        "Can you send me options?",
        "I want something in Dubai.",
        "Do you have any good deals?",
        "Can you send location?",
        "I commented on your TikTok.",
        "I need details on WhatsApp.",
        "What is the best area?",
      ],
      response: ({ need, intent, area }) =>
        `Sure. Are you looking to ${intent} a ${need} in ${area}, or are you still comparing areas? May I know your budget range first?`,
      focus: "先把客户从 vague interest 拉到 buy/rent、户型、区域、预算。",
      vocab: ["budget range", "preferred area", "unit type", "requirements", "timeline"],
    },
    {
      id: "buyer",
      tag: "Buyer investment",
      role: "Buyer",
      themes: ["investment lead", "cash buyer", "mortgage buyer", "ROI question", "first-time buyer"],
      needs: ["studio", "1-bedroom", "2-bedroom", "off-plan unit", "ready unit"],
      intents: ["buy for investment", "buy for personal use", "buy with mortgage", "buy off-plan", "buy ready property"],
      areas: ["JVC", "Business Bay", "Dubai Creek Harbour", "Dubai Hills", "Meydan", "Emaar South", "Arjan", "MBR City", "Downtown Dubai", "Dubai Marina"],
      questions: [
        "Is this good for investment?",
        "Can you guarantee ROI?",
        "Which area has better rental demand?",
        "I want capital appreciation.",
        "Should I buy off-plan or ready?",
        "What is the expected rental income?",
        "Is the entry price good?",
        "I want to invest around 1M AED.",
        "Which developer is safer?",
        "Can I resell before handover?",
      ],
      response: ({ need, area }) =>
        `It can be worth comparing, but I cannot guarantee ROI. For a ${need} in ${area}, we should check entry price, rental demand, payment plan, and handover timeline.`,
      focus: "投资客户要讲分析维度，不承诺收益。",
      vocab: ["rental demand", "entry price", "capital appreciation", "handover", "payment plan"],
    },
    {
      id: "rental",
      tag: "Rental communication",
      role: "Tenant",
      themes: ["long-term rental", "short-term rental", "family rental", "move-in request", "viewing request"],
      needs: ["studio", "1-bedroom", "2-bedroom", "3-bedroom", "furnished unit"],
      intents: ["move in soon", "rent monthly", "rent yearly", "short-term stay", "schedule a viewing"],
      areas: ["JVC", "Dubai Marina", "JLT", "Business Bay", "Downtown Dubai", "Al Barsha", "Arjan", "Dubai Silicon Oasis", "Damac Hills", "Dubai Hills"],
      questions: [
        "I need to move in this month.",
        "Do you have yearly rental?",
        "Is it furnished?",
        "Can I view it tomorrow?",
        "What is the rent and deposit?",
        "Is chiller included?",
        "Can I pay by cheques?",
        "Do you allow pets?",
        "Is it near metro?",
        "I need a short-term rental.",
      ],
      response: ({ need, area, intent }) =>
        `Sure. For a ${need} in ${area}, may I know your move-in date, budget, and whether you prefer furnished or unfurnished? Then we can check suitable options for ${intent}.`,
      focus: "租房先问入住时间、预算、家具、付款方式。",
      vocab: ["move-in date", "furnished", "unfurnished", "security deposit", "viewing"],
    },
    {
      id: "agent",
      tag: "Agent collaboration",
      role: "Agent",
      themes: ["video request", "lead update", "availability check", "viewing coordination", "material request"],
      needs: ["property video", "floor plan", "latest price", "availability", "viewing time"],
      intents: ["send today", "confirm status", "align next step", "update after call", "schedule a quick call"],
      areas: ["JVC", "Business Bay", "Dubai Marina", "Downtown Dubai", "Arjan", "Dubai Hills", "Meydan", "JLT", "Damac Hills", "Palm Jumeirah"],
      questions: [
        "I will send it later.",
        "The client asked for more details.",
        "The unit may not be available.",
        "Can we discuss this lead?",
        "I need more information from the client.",
        "Should I follow up today?",
        "The client wants a viewing.",
        "I have a new project to share.",
        "What content do you need?",
        "The price changed.",
      ],
      response: ({ need, intent, area }) =>
        `Thanks. Could you please ${intent} and share the ${need} for ${area}? We need the latest details before following up with the lead.`,
      focus: "和 agent 沟通要明确事项、截止时间、用途和下一步。",
      vocab: ["latest status", "availability", "lead follow-up", "align", "Dubai time"],
    },
    {
      id: "partner",
      tag: "Business partnership",
      role: "Partner",
      themes: ["new partnership", "commission discussion", "exclusive lead request", "lead quality", "pilot cooperation"],
      needs: ["shared leads", "exclusive leads", "qualified leads", "commission model", "conversion review"],
      intents: ["start cooperation", "test the process", "review quality", "discuss commission", "align expectations"],
      areas: ["Dubai", "Dubai market", "off-plan market", "ready market", "rental market", "luxury market", "JVC", "Business Bay", "Dubai Marina", "Downtown Dubai"],
      questions: [
        "How do you work with agents?",
        "Can you provide exclusive leads?",
        "What is your commission model?",
        "What kind of clients do you have?",
        "How do you qualify leads?",
        "Can we start this week?",
        "Do you work with many agents?",
        "How do you share leads?",
        "What is the follow-up process?",
        "Can we sign an agreement?",
      ],
      response: ({ need, intent }) =>
        `We can ${intent} with ${need} first. Our focus is lead generation and qualification, and partner agents handle property details, viewings, and closing.`,
      focus: "商务合作先讲清定位和分工，不把自己说成持有房源的中介。",
      vocab: ["qualified leads", "commission model", "conversion quality", "partner agent", "follow-up process"],
    },
    {
      id: "project",
      tag: "Project introduction",
      role: "Client",
      themes: ["project overview", "price explanation", "payment plan", "handover timeline", "developer question"],
      needs: ["location", "starting price", "payment plan", "unit mix", "handover date"],
      intents: ["understand the project", "compare projects", "check investment fit", "ask developer", "review details"],
      areas: ["JVC", "Business Bay", "Dubai Creek Harbour", "Dubai Hills", "Meydan", "Arjan", "Downtown Dubai", "Dubai Marina", "Emaar South", "MBR City"],
      questions: [
        "Can you tell me more about this project?",
        "Where is it located?",
        "What is the starting price?",
        "Is there a payment plan?",
        "When is the handover?",
        "Who is the developer?",
        "What unit types are available?",
        "Is it good for rental?",
        "What amenities does it have?",
        "Is the price negotiable?",
      ],
      response: ({ need, area }) =>
        `This project is in ${area}. The key points to check are ${need}, unit size, current availability, payment plan, and expected handover before making a decision.`,
      focus: "介绍楼盘先讲事实，不堆 luxury/amazing/best deal。",
      vocab: ["starting price", "payment plan", "handover", "amenities", "developer"],
    },
    {
      id: "content",
      tag: "Content operations",
      role: "Agent",
      themes: ["video shooting", "caption writing", "content review", "missing material", "posting plan"],
      needs: ["entrance shot", "living room video", "balcony view", "floor plan", "project highlights"],
      intents: ["record the video", "send before posting", "write a caption", "confirm details", "prepare content"],
      areas: ["JVC", "Business Bay", "Dubai Marina", "Downtown Dubai", "Dubai Hills", "Arjan", "JLT", "Meydan", "Palm Jumeirah", "Damac Hills"],
      questions: [
        "What should I record?",
        "Can you write a caption?",
        "Is this video enough?",
        "What details are missing?",
        "Can we post this today?",
        "Should we mention the price?",
        "Do you need the floor plan?",
        "Which angle should I shoot?",
        "Can you make it more attractive?",
        "What should be the hook?",
      ],
      response: ({ need, intent, area }) =>
        `For ${area}, please ${intent} and include the ${need}, unit type, starting price, payment plan, and one clear reason why the project is relevant to buyers.`,
      focus: "内容运营要把视频素材变成线索转化，不是只写漂亮文案。",
      vocab: ["caption", "hook", "highlight", "floor plan", "posting"],
    },
    {
      id: "team",
      tag: "Daily work",
      role: "Team",
      themes: ["daily update", "task priority", "blocker", "handover", "follow-up plan"],
      needs: ["lead status", "content plan", "agent reply", "next step", "deadline"],
      intents: ["give an update", "prioritize tasks", "explain delay", "handover work", "confirm ownership"],
      areas: ["today", "this morning", "this afternoon", "Dubai time", "tomorrow", "this week", "before posting", "after the call", "before 5 PM", "by end of day"],
      questions: [
        "Any updates today?",
        "Which task should we do first?",
        "Why is this delayed?",
        "Can you take over this lead?",
        "What is the next step?",
        "Who is following up?",
        "Can we finish it today?",
        "What is blocking this?",
        "Please update the team.",
        "Can you summarize the progress?",
      ],
      response: ({ need, intent, area }) =>
        `Quick update: I will ${intent} for the ${need} ${area}. The main next step is to confirm the latest information and follow up clearly.`,
      focus: "团队沟通要短、清楚、可执行。",
      vocab: ["quick update", "blocker", "priority", "take over", "next step"],
    },
    {
      id: "objection",
      tag: "Client objection",
      role: "Client",
      themes: ["trust issue", "low budget", "not ready", "too expensive", "needs time"],
      needs: ["more proof", "lower budget", "more time", "different area", "clear explanation"],
      intents: ["reduce pressure", "clarify concern", "keep the lead warm", "ask one useful question", "offer to update later"],
      areas: ["Dubai", "JVC", "Business Bay", "Dubai Marina", "Downtown Dubai", "Dubai Hills", "ready units", "off-plan projects", "rental options", "investment options"],
      questions: [
        "This is too expensive.",
        "I am not ready yet.",
        "How do I know this is real?",
        "I need to think about it.",
        "My budget is lower.",
        "I do not want agents to spam me.",
        "Can you give me a discount?",
        "I am just checking.",
        "I already have an agent.",
        "I am worried about risk.",
      ],
      response: ({ need, intent, area }) =>
        `I understand. We can ${intent} first and focus only on ${need} in ${area}. No pressure; I just want to understand what would actually work for you.`,
      focus: "处理异议要降低压力、确认顾虑、保留沟通。",
      vocab: ["no pressure", "concern", "risk", "suitable", "work for you"],
    },
    {
      id: "social",
      tag: "Social English",
      role: "Partner",
      themes: ["small talk", "meeting opening", "relationship building", "polite reply", "casual follow-up"],
      needs: ["quick greeting", "meeting time", "weekend comment", "thank-you message", "polite check-in"],
      intents: ["sound natural", "keep it friendly", "open the conversation", "reply politely", "close the chat"],
      areas: ["today", "this week", "after the meeting", "before the call", "on WhatsApp", "in Dubai time", "in the group", "with the agent", "with the client", "with the partner"],
      questions: [
        "How are you?",
        "Hope you are doing well.",
        "Can we talk later?",
        "Thanks for your help.",
        "Sorry for the late reply.",
        "Are you free for a quick call?",
        "Have a good weekend.",
        "Let me know when you are free.",
        "Nice speaking with you.",
        "Just checking in.",
      ],
      response: ({ need, intent, area }) =>
        `Sure, ${intent}. Thanks for the ${need} ${area}. Let me check and I will get back to you shortly.`,
      focus: "日常 social 英语要自然轻松，不要像正式邮件。",
      vocab: ["quick call", "checking in", "no worries", "get back to you", "sounds good"],
    },
  ];

  const lessons = {};
  categories.forEach((category) => {
    for (let index = 0; index < 100; index += 1) {
      const theme = category.themes[index % category.themes.length];
      const need = category.needs[(index + Math.floor(index / 10)) % category.needs.length];
      const intent = category.intents[(index + Math.floor(index / 5)) % category.intents.length];
      const area = category.areas[(index + Math.floor(index / 3)) % category.areas.length];
      const question = category.questions[index % category.questions.length];
      const model = category.response({ theme, need, intent, area, question, index });
      const id = `seed_${category.id}_${String(index + 1).padStart(3, "0")}`;
      const title = `${theme}：${need}`;
      const phrase = model.split(".")[0].trim() + ".";
      lessons[id] = {
        tag: category.tag,
        title,
        context: `种子知识库：${category.focus}`,
        sourceRole: category.role,
        source: question,
        model,
        breakdown: `${category.focus} 这个场景的关键不是背单词，而是用一句自然英文把对话推进到下一步。`,
        pronunciation: {
          phrase,
          hint: "点击英文单词可读单词；点击句子后的喇叭可读整句。",
          parts: phrase.replaceAll(",", " /").replaceAll(".", ""),
          tip: "先跟读整句，再回到真实工作场景里使用。",
        },
        vocab: category.vocab.map((word) => [word, vocabularyMeaning(word)]),
        sentences: [
          [phrase, "本知识点核心句"],
          ["Could you share a bit more context?", "让对方补充背景"],
          ["Let me check the latest details first.", "先核实最新信息"],
          ["What would be the best next step?", "确认下一步"],
        ],
        drills: [
          [model, "完整示范回复"],
          [`Could you confirm the ${need}?`, "确认关键信息"],
          [`Let's align on this ${area}.`, "同步当前事项"],
          ["I will follow up shortly.", "稍后跟进"],
        ],
        mistake: "不要逐字硬翻中文；不要过早承诺价格、房源、收益或结果。",
        usage: phrase,
        examTask: `AI 扮演 ${category.role}。你要围绕 ${theme} 用自然英文继续沟通，并完成真实工作推进。`,
        checklist: [
          ["自然", "像 WhatsApp/飞书里的真人工作沟通"],
          ["推进", "问清信息、确认下一步或给出明确回复"],
          ["边界", "不虚构房源，不承诺收益，不夸张销售"],
        ],
        daily: `学会一句：${phrase}`,
        examRounds: [
          `${category.role}: ${question}`,
          `${category.role}: Can you explain a bit more?`,
          `${category.role}: What should we do next?`,
          `${category.role}: Can you send me the details?`,
        ],
        feedback: "重点看三件事：表达是否自然、信息是否清楚、是否推进了下一步。",
        sourceOrigin: "manual-seed-library",
      };
    }
  });
  return lessons;
})();

function vocabularyMeaning(word) {
  const meanings = {
    "budget range": "预算范围",
    "preferred area": "偏好区域",
    "unit type": "户型/房源类型",
    requirements: "需求",
    timeline: "时间线",
    "rental demand": "租赁需求",
    "entry price": "入手价格",
    "capital appreciation": "资产升值",
    handover: "交房",
    "payment plan": "付款计划",
    "move-in date": "入住日期",
    furnished: "带家具",
    unfurnished: "不带家具",
    "security deposit": "押金",
    viewing: "看房",
    "latest status": "最新进展",
    availability: "是否可售/可租",
    "lead follow-up": "线索跟进",
    align: "同步",
    "Dubai time": "迪拜时间",
    "qualified leads": "筛选过的线索",
    "commission model": "佣金模式",
    "conversion quality": "转化质量",
    "partner agent": "合作经纪人",
    "follow-up process": "跟进流程",
    "starting price": "起价",
    amenities: "配套设施",
    developer: "开发商",
    caption: "视频文案",
    hook: "开头钩子",
    highlight: "亮点",
    "floor plan": "户型图",
    posting: "发布",
    "quick update": "快速同步",
    blocker: "卡点",
    priority: "优先级",
    "take over": "接手",
    "next step": "下一步",
    "no pressure": "不用有压力",
    concern: "顾虑",
    risk: "风险",
    suitable: "合适的",
    "work for you": "适合你",
    "quick call": "短电话/短会",
    "checking in": "轻量跟进",
    "no worries": "没关系",
    "get back to you": "回复你",
    "sounds good": "听起来可以",
  };
  return meanings[word] || "工作场景高频表达";
}

window.BUSINESS_KNOWLEDGE_BASE = BUSINESS_KNOWLEDGE_BASE;
